#!/usr/bin/env python3
"""Generates lib/core/theme/omarchy_themes.dart from an Omarchy checkout.

Every theme's colors.toml is resolved with Omarchy's own resolver
(bin/omarchy-theme-color --all), so the bundled palettes carry exactly the
values Omarchy bakes into its alacritty/kitty/ghostty configs.

Usage: tools/generate_omarchy_themes.py <omarchy-checkout> [commit]
Omarchy is MIT licensed (c) David Heinemeier Hansson.
"""
import os
import subprocess
import sys

FIELDS = [
    ('accent', 'accent'),
    ('background', 'background'),
    ('foreground', 'foreground'),
    ('selection', 'selection'),
    ('selection_foreground', 'selectionForeground'),
    ('muted', 'muted'),
    ('dark_background', 'darkBackground'),
    ('darker_background', 'darkerBackground'),
    ('lighter_background', 'lighterBackground'),
    ('dark_foreground', 'darkForeground'),
    ('light_foreground', 'lightForeground'),
    ('bright_foreground', 'brightForeground'),
    ('red', 'red'),
    ('green', 'green'),
    ('yellow', 'yellow'),
    ('blue', 'blue'),
    ('magenta', 'magenta'),
    ('cyan', 'cyan'),
    ('orange', 'orange'),
    ('bright_red', 'brightRed'),
    ('bright_green', 'brightGreen'),
    ('bright_yellow', 'brightYellow'),
    ('bright_blue', 'brightBlue'),
    ('bright_magenta', 'brightMagenta'),
    ('bright_cyan', 'brightCyan'),
]


def camel(slug):
    head, *rest = slug.split('-')
    return head + ''.join(part.capitalize() for part in rest)


def label(slug):
    return ' '.join(part.capitalize() for part in slug.split('-'))


def color(value):
    value = value.strip().lstrip('#')
    if len(value) != 6:
        raise SystemExit(f'unexpected colour {value!r}')
    return f'Color(0xFF{value.upper()})'


def main():
    root = sys.argv[1]
    commit = sys.argv[2] if len(sys.argv) > 2 else 'unknown'
    themes_dir = os.path.join(root, 'themes')
    resolver = os.path.join(root, 'bin', 'omarchy-theme-color')
    out = [
        '// GENERATED by tools/generate_omarchy_themes.py. Do not edit by hand.',
        '//',
        '// Source: https://github.com/basecamp/omarchy themes/*/colors.toml at',
        f'// commit {commit}, resolved with bin/omarchy-theme-color --all.',
        '// Omarchy is MIT licensed, Copyright (c) David Heinemeier Hansson.',
        '',
        "import 'package:conduit/core/theme/omarchy_colors.dart';",
        "import 'package:flutter/painting.dart';",
        '',
    ]
    slugs = sorted(os.listdir(themes_dir))
    for slug in slugs:
        colors_file = os.path.join(themes_dir, slug, 'colors.toml')
        resolved = subprocess.run(
            ['bash', resolver, '--file', colors_file, '--all'],
            check=True, capture_output=True, text=True,
        ).stdout
        values = dict(line.split('\t', 1) for line in resolved.splitlines() if '\t' in line)
        out.append(f'/// {label(slug)} (themes/{slug}/colors.toml).')
        out.append(f'const OmarchyColors omarchy{camel(slug)[0].upper() + camel(slug)[1:]} = OmarchyColors(')
        out.append(f"  mode: OmarchyMode.{values['mode']},")
        for key, field in FIELDS:
            out.append(f'  {field}: {color(values[key])},')
        out.append(');')
        out.append('')
    out.append('/// Every theme Omarchy ships, keyed by its directory name.')
    out.append('const Map<String, OmarchyColors> omarchyBundledThemes = {')
    for slug in slugs:
        out.append(f"  '{slug}': omarchy{camel(slug)[0].upper() + camel(slug)[1:]},")
    out.append('};')
    out.append('')
    target = os.path.join(os.path.dirname(__file__), '..', 'lib', 'core', 'theme', 'omarchy_themes.dart')
    with open(target, 'w') as handle:
        handle.write('\n'.join(out))


if __name__ == '__main__':
    main()
